# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutUI(object):
    def setupUi(self, AboutUI):
        AboutUI.setObjectName("AboutUI")
        AboutUI.resize(550, 470)
        self.verticalLayout = QtWidgets.QVBoxLayout(AboutUI)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(AboutUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textBrowser = QtWidgets.QTextBrowser(AboutUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setStyleSheet("QTextBrowser {\n"
"border: 0.5px solid grey;\n"
"border-radius:2px;\n"
"}\n"
"\n"
"")
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_4.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.developer_info = QtWidgets.QTextBrowser(AboutUI)
        self.developer_info.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.developer_info.sizePolicy().hasHeightForWidth())
        self.developer_info.setSizePolicy(sizePolicy)
        self.developer_info.setStyleSheet("QTextBrowser {\n"
"border: 0.5px solid grey;\n"
"border-radius:2px;\n"
"}\n"
"\n"
"")
        self.developer_info.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.developer_info.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.developer_info.setReadOnly(True)
        self.developer_info.setOpenExternalLinks(True)
        self.developer_info.setObjectName("developer_info")
        self.gridLayout_4.addWidget(self.developer_info, 0, 1, 1, 1)
        self.horizontalLayout_23.addLayout(self.gridLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.warlordsoft_button_3 = QtWidgets.QPushButton(AboutUI)
        self.warlordsoft_button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.warlordsoft_button_3.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/myresource/resource/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.warlordsoft_button_3.setIcon(icon)
        self.warlordsoft_button_3.setIconSize(QtCore.QSize(18, 18))
        self.warlordsoft_button_3.setObjectName("warlordsoft_button_3")
        self.horizontalLayout_16.addWidget(self.warlordsoft_button_3)
        self.rate_button_3 = QtWidgets.QPushButton(AboutUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rate_button_3.sizePolicy().hasHeightForWidth())
        self.rate_button_3.setSizePolicy(sizePolicy)
        self.rate_button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rate_button_3.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/myresource/resource/facebook-like.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rate_button_3.setIcon(icon1)
        self.rate_button_3.setIconSize(QtCore.QSize(18, 18))
        self.rate_button_3.setObjectName("rate_button_3")
        self.horizontalLayout_16.addWidget(self.rate_button_3)
        self.feedback_button_3 = QtWidgets.QPushButton(AboutUI)
        self.feedback_button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.feedback_button_3.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/myresource/resource/person-growth.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.feedback_button_3.setIcon(icon2)
        self.feedback_button_3.setIconSize(QtCore.QSize(18, 18))
        self.feedback_button_3.setObjectName("feedback_button_3")
        self.horizontalLayout_16.addWidget(self.feedback_button_3)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.donate_button_3 = QtWidgets.QPushButton(AboutUI)
        self.donate_button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.donate_button_3.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/myresource/resource/paypal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.donate_button_3.setIcon(icon3)
        self.donate_button_3.setIconSize(QtCore.QSize(18, 18))
        self.donate_button_3.setObjectName("donate_button_3")
        self.verticalLayout.addWidget(self.donate_button_3)
        self.ge_more_apps_3 = QtWidgets.QPushButton(AboutUI)
        self.ge_more_apps_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ge_more_apps_3.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/myresource/resource/user-male--v1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ge_more_apps_3.setIcon(icon4)
        self.ge_more_apps_3.setIconSize(QtCore.QSize(18, 18))
        self.ge_more_apps_3.setObjectName("ge_more_apps_3")
        self.verticalLayout.addWidget(self.ge_more_apps_3)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(AboutUI)
        QtCore.QMetaObject.connectSlotsByName(AboutUI)

    def retranslateUi(self, AboutUI):
        _translate = QtCore.QCoreApplication.translate
        AboutUI.setWindowTitle(_translate("AboutUI", "Form"))
        self.label.setText(_translate("AboutUI", "About"))
        self.textBrowser.setHtml(_translate("AboutUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/myresource/resource/icon.png\" width=\"70\" height=\"70\" /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#d1d1d1;\">Y2MATE PRO</span><span style=\" color:#d1d1d1;\"> For Linux Desktop</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#d1d1d1;\">Developer Email:</span><span style=\" color:#d1d1d1;\"> </span><a href=\"mailto: contact@warlordsoftwares.in\"><span style=\" text-decoration: underline; color:#d1d1d1;\">contact@warlordsoftwares.in</span></a></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#d1d1d1;\">Version: 0.2 </span><span style=\" color:#d1d1d1;\">|</span><span style=\" font-weight:600; color:#d1d1d1;\"> Language used: </span><span style=\" color:#d1d1d1;\">Python (PyQt5)</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#d1d1d1;\"><br /></p></body></html>"))
        self.developer_info.setHtml(_translate("AboutUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/myresource/resource/user_blue.png\" width=\"100\" height=\"100\" /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#d1d1d1;\">Developed by:</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#d1d1d1;\">Rishabh Bhardwaj (S.D.E)</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#d1d1d1;\">Checkout </span><a href=\"https://github.com/rishabh3354\"><span style=\" text-decoration: underline; color:#d1d1d1;\">GitHub</span></a><span style=\" font-weight:600; color:#d1d1d1;\"> | </span><a href=\"https://www.buymeacoffee.com/rishabh33\"><span style=\" text-decoration: underline; color:#d1d1d1;\">BuyMeCoffee</span></a></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#d1d1d1;\"><br /></p></body></html>"))
        self.warlordsoft_button_3.setText(_translate("AboutUI", "Visit @WarlordSoft"))
        self.rate_button_3.setText(_translate("AboutUI", "Rate"))
        self.feedback_button_3.setText(_translate("AboutUI", "Feedback"))
        self.donate_button_3.setText(_translate("AboutUI", "Donate"))
        self.ge_more_apps_3.setText(_translate("AboutUI", "Get More Apps"))
import resource_rc
