# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'account.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountUI(object):
    def setupUi(self, AccountUI):
        AccountUI.setObjectName("AccountUI")
        AccountUI.resize(733, 773)
        self.verticalLayout = QtWidgets.QVBoxLayout(AccountUI)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(AccountUI)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(AccountUI)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.account_progress_bar = QtWidgets.QProgressBar(AccountUI)
        self.account_progress_bar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_progress_bar.sizePolicy().hasHeightForWidth())
        self.account_progress_bar.setSizePolicy(sizePolicy)
        self.account_progress_bar.setAutoFillBackground(False)
        self.account_progress_bar.setStyleSheet("QProgressBar:horizontal {\n"
"background:rgba(0,0,0,0.1);\n"
"color: white;\n"
"background-color: rgba(49, 54, 59, 1);\n"
"height: 1px;\n"
"\n"
"\n"
"}\n"
"QProgressBar::chunk:horizontal {\n"
"background:rgb(0, 153, 255);\n"
"color: white;\n"
"\n"
"}\n"
"QProgressBar \n"
"{ \n"
"color: white; \n"
"}\n"
"")
        self.account_progress_bar.setMaximum(100)
        self.account_progress_bar.setProperty("value", 100)
        self.account_progress_bar.setTextVisible(True)
        self.account_progress_bar.setObjectName("account_progress_bar")
        self.verticalLayout.addWidget(self.account_progress_bar)
        self.scrollArea = QtWidgets.QScrollArea(AccountUI)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 699, 696))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_16.addItem(spacerItem)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_plan = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_plan.setEnabled(True)
        self.lineEdit_plan.setStyleSheet("QLineEdit {\n"
"padding: 6px;\n"
"}\n"
"\n"
"")
        self.lineEdit_plan.setReadOnly(True)
        self.lineEdit_plan.setObjectName("lineEdit_plan")
        self.gridLayout_3.addWidget(self.lineEdit_plan, 1, 1, 1, 1)
        self.lineEdit_expires_on = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_expires_on.setEnabled(True)
        self.lineEdit_expires_on.setStyleSheet("QLineEdit {\n"
"padding: 6px;\n"
"}\n"
"\n"
"")
        self.lineEdit_expires_on.setReadOnly(True)
        self.lineEdit_expires_on.setObjectName("lineEdit_expires_on")
        self.gridLayout_3.addWidget(self.lineEdit_expires_on, 2, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"padding: 6px;\n"
"}\n"
"\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.lineEdit_account_id = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_account_id.setEnabled(True)
        self.lineEdit_account_id.setStyleSheet("QLineEdit {\n"
"padding: 6px;\n"
"}\n"
"\n"
"")
        self.lineEdit_account_id.setReadOnly(True)
        self.lineEdit_account_id.setObjectName("lineEdit_account_id")
        self.gridLayout_3.addWidget(self.lineEdit_account_id, 0, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
"padding: 6px;\n"
"}\n"
"\n"
"")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_3.addWidget(self.lineEdit_7, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"padding: 6px;\n"
"}\n"
"\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 1, 0, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_3)
        self.verticalLayout_16.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.error_message = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_message.sizePolicy().hasHeightForWidth())
        self.error_message.setSizePolicy(sizePolicy)
        self.error_message.setAlignment(QtCore.Qt.AlignCenter)
        self.error_message.setObjectName("error_message")
        self.verticalLayout_2.addWidget(self.error_message)
        self.groupBox_10 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        spacerItem1 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_17.addItem(spacerItem1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.purchase_licence = QtWidgets.QPushButton(self.groupBox_10)
        self.purchase_licence.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.purchase_licence.sizePolicy().hasHeightForWidth())
        self.purchase_licence.setSizePolicy(sizePolicy)
        self.purchase_licence.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.purchase_licence.setStyleSheet("QPushButton{\n"
"  background-color:#d23426;\n"
"\n"
"\n"
"\n"
"color:#eff0f1;\n"
"\n"
"\n"
"}\n"
"    \n"
"QPushButton:hover {background-color: #009b22\n"
"\n"
"\n"
"\n"
"\n"
"\n"
";}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/myresource/resource/shopping-cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.purchase_licence.setIcon(icon)
        self.purchase_licence.setIconSize(QtCore.QSize(25, 25))
        self.purchase_licence.setObjectName("purchase_licence")
        self.horizontalLayout_17.addWidget(self.purchase_licence)
        self.refresh_account = QtWidgets.QPushButton(self.groupBox_10)
        self.refresh_account.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh_account.sizePolicy().hasHeightForWidth())
        self.refresh_account.setSizePolicy(sizePolicy)
        self.refresh_account.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refresh_account.setStyleSheet("QPushButton{\n"
"  background-color: #018282;\n"
"\n"
"\n"
"\n"
"\n"
"color:#eff0f1;\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #009b22\n"
"\n"
"\n"
"\n"
"\n"
"\n"
";}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/myresource/resource/refresh--v1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_account.setIcon(icon1)
        self.refresh_account.setIconSize(QtCore.QSize(25, 25))
        self.refresh_account.setObjectName("refresh_account")
        self.horizontalLayout_17.addWidget(self.refresh_account)
        self.verticalLayout_17.addLayout(self.horizontalLayout_17)
        self.verticalLayout_2.addWidget(self.groupBox_10)
        self.groupBox_12 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_12.sizePolicy().hasHeightForWidth())
        self.groupBox_12.setSizePolicy(sizePolicy)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        spacerItem2 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_19.addItem(spacerItem2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_12)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_12)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 10, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_12)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 4, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_13.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setStyleSheet("")
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_5.addWidget(self.lineEdit_13, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_12)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_12)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 8, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_3.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 2, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_8.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("")
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_5.addWidget(self.lineEdit_8, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_12)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_12)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 9, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_12)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 7, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton_14 = QtWidgets.QToolButton(self.groupBox_12)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/myresource/resource/icons8-double-tick-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_14.setIcon(icon2)
        self.toolButton_14.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_14.setObjectName("toolButton_14")
        self.horizontalLayout.addWidget(self.toolButton_14)
        self.gridLayout_5.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toolButton_15 = QtWidgets.QToolButton(self.groupBox_12)
        self.toolButton_15.setIcon(icon2)
        self.toolButton_15.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_15.setObjectName("toolButton_15")
        self.horizontalLayout_3.addWidget(self.toolButton_15)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 4, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButton_48 = QtWidgets.QToolButton(self.groupBox_12)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/myresource/resource/icons8-multiply-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_48.setIcon(icon3)
        self.toolButton_48.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_48.setObjectName("toolButton_48")
        self.horizontalLayout_4.addWidget(self.toolButton_48)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 5, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toolButton_49 = QtWidgets.QToolButton(self.groupBox_12)
        self.toolButton_49.setIcon(icon3)
        self.toolButton_49.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_49.setObjectName("toolButton_49")
        self.horizontalLayout_5.addWidget(self.toolButton_49)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 6, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toolButton_16 = QtWidgets.QToolButton(self.groupBox_12)
        self.toolButton_16.setIcon(icon2)
        self.toolButton_16.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_16.setObjectName("toolButton_16")
        self.horizontalLayout_6.addWidget(self.toolButton_16)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 3, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.toolButton_17 = QtWidgets.QToolButton(self.groupBox_12)
        self.toolButton_17.setIcon(icon2)
        self.toolButton_17.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_17.setObjectName("toolButton_17")
        self.horizontalLayout_7.addWidget(self.toolButton_17)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 4, 2, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.toolButton_18 = QtWidgets.QToolButton(self.groupBox_12)
        self.toolButton_18.setIcon(icon2)
        self.toolButton_18.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_18.setObjectName("toolButton_18")
        self.horizontalLayout_8.addWidget(self.toolButton_18)
        self.gridLayout_5.addLayout(self.horizontalLayout_8, 5, 2, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.toolButton_19 = QtWidgets.QToolButton(self.groupBox_12)
        self.toolButton_19.setIcon(icon2)
        self.toolButton_19.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_19.setObjectName("toolButton_19")
        self.horizontalLayout_9.addWidget(self.toolButton_19)
        self.gridLayout_5.addLayout(self.horizontalLayout_9, 6, 2, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.toolButton_20 = QtWidgets.QToolButton(self.groupBox_12)
        self.toolButton_20.setIcon(icon2)
        self.toolButton_20.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_20.setObjectName("toolButton_20")
        self.horizontalLayout_12.addWidget(self.toolButton_20)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 7, 2, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.toolButton_21 = QtWidgets.QToolButton(self.groupBox_12)
        self.toolButton_21.setIcon(icon2)
        self.toolButton_21.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_21.setObjectName("toolButton_21")
        self.horizontalLayout_13.addWidget(self.toolButton_21)
        self.gridLayout_5.addLayout(self.horizontalLayout_13, 8, 2, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.toolButton_22 = QtWidgets.QToolButton(self.groupBox_12)
        self.toolButton_22.setIcon(icon2)
        self.toolButton_22.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_22.setObjectName("toolButton_22")
        self.horizontalLayout_14.addWidget(self.toolButton_22)
        self.gridLayout_5.addLayout(self.horizontalLayout_14, 9, 2, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.toolButton_23 = QtWidgets.QToolButton(self.groupBox_12)
        self.toolButton_23.setIcon(icon2)
        self.toolButton_23.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_23.setObjectName("toolButton_23")
        self.horizontalLayout_15.addWidget(self.toolButton_23)
        self.gridLayout_5.addLayout(self.horizontalLayout_15, 10, 2, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.toolButton_24 = QtWidgets.QToolButton(self.groupBox_12)
        self.toolButton_24.setIcon(icon2)
        self.toolButton_24.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_24.setObjectName("toolButton_24")
        self.horizontalLayout_16.addWidget(self.toolButton_24)
        self.gridLayout_5.addLayout(self.horizontalLayout_16, 7, 1, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.toolButton_50 = QtWidgets.QToolButton(self.groupBox_12)
        self.toolButton_50.setIcon(icon3)
        self.toolButton_50.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_50.setObjectName("toolButton_50")
        self.horizontalLayout_18.addWidget(self.toolButton_50)
        self.gridLayout_5.addLayout(self.horizontalLayout_18, 8, 1, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.toolButton_51 = QtWidgets.QToolButton(self.groupBox_12)
        self.toolButton_51.setIcon(icon3)
        self.toolButton_51.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_51.setObjectName("toolButton_51")
        self.horizontalLayout_19.addWidget(self.toolButton_51)
        self.gridLayout_5.addLayout(self.horizontalLayout_19, 9, 1, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.toolButton_52 = QtWidgets.QToolButton(self.groupBox_12)
        self.toolButton_52.setIcon(icon3)
        self.toolButton_52.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_52.setObjectName("toolButton_52")
        self.horizontalLayout_20.addWidget(self.toolButton_52)
        self.gridLayout_5.addLayout(self.horizontalLayout_20, 10, 1, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_5)
        self.verticalLayout_19.addLayout(self.horizontalLayout_11)
        self.verticalLayout_2.addWidget(self.groupBox_12)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout.addLayout(self.verticalLayout_14)

        self.retranslateUi(AccountUI)
        QtCore.QMetaObject.connectSlotsByName(AccountUI)

    def retranslateUi(self, AccountUI):
        _translate = QtCore.QCoreApplication.translate
        AccountUI.setWindowTitle(_translate("AccountUI", "Form"))
        self.label_6.setText(_translate("AccountUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:18pt; font-weight:600; color:#888a85;\">ACCOUNT INFO</span></p></body></html>"))
        self.label_5.setText(_translate("AccountUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/myresource/resource/icons8-account-96.png\" width=\"45\"/></p></body></html>"))
        self.groupBox_9.setTitle(_translate("AccountUI", "ACCOUNT DETAILS"))
        self.lineEdit_plan.setText(_translate("AccountUI", "Evaluation"))
        self.lineEdit_expires_on.setText(_translate("AccountUI", "Licence Expired! Purchase a new Licence"))
        self.lineEdit.setText(_translate("AccountUI", "Account ID:"))
        self.lineEdit_account_id.setText(_translate("AccountUI", "8fjfdjhqoifj383ld"))
        self.lineEdit_7.setText(_translate("AccountUI", "Account Status:"))
        self.lineEdit_2.setText(_translate("AccountUI", "Account Type:"))
        self.error_message.setText(_translate("AccountUI", "<html><head/><body><p align=\"center\"><span style=\" color:#ef2929;\">Error Message</span></p></body></html>"))
        self.groupBox_10.setTitle(_translate("AccountUI", "PURCHASE LICENSE"))
        self.purchase_licence.setText(_translate("AccountUI", "PURCHASE NOW"))
        self.refresh_account.setText(_translate("AccountUI", "REFRESH ACCOUNT"))
        self.groupBox_12.setTitle(_translate("AccountUI", "FREE vs PRO"))
        self.label_2.setText(_translate("AccountUI", "➤ Protect PDF"))
        self.label_11.setText(_translate("AccountUI", "➤ Page numbering support"))
        self.label_3.setText(_translate("AccountUI", "➤ Support Auto orientation"))
        self.lineEdit_13.setText(_translate("AccountUI", "FREE VERSION"))
        self.label_10.setText(_translate("AccountUI", "➤ Adjust image position on page"))
        self.label_8.setText(_translate("AccountUI", "➤ Set DPI of image"))
        self.lineEdit_3.setText(_translate("AccountUI", "LIST OF FEATURES"))
        self.lineEdit_8.setText(_translate("AccountUI", "PRO/EVALUATION"))
        self.label_4.setText(_translate("AccountUI", "➤ Set page margin"))
        self.label_12.setText(_translate("AccountUI", "➤ Rotate pdf pages"))
        self.label_9.setText(_translate("AccountUI", "➤ Support Auto Page format"))
        self.toolButton_14.setText(_translate("AccountUI", "..."))
        self.toolButton_15.setText(_translate("AccountUI", "..."))
        self.toolButton_48.setText(_translate("AccountUI", "..."))
        self.toolButton_49.setText(_translate("AccountUI", "..."))
        self.toolButton_16.setText(_translate("AccountUI", "..."))
        self.toolButton_17.setText(_translate("AccountUI", "..."))
        self.toolButton_18.setText(_translate("AccountUI", "..."))
        self.toolButton_19.setText(_translate("AccountUI", "..."))
        self.toolButton_20.setText(_translate("AccountUI", "..."))
        self.toolButton_21.setText(_translate("AccountUI", "..."))
        self.toolButton_22.setText(_translate("AccountUI", "..."))
        self.toolButton_23.setText(_translate("AccountUI", "..."))
        self.toolButton_24.setText(_translate("AccountUI", "..."))
        self.toolButton_50.setText(_translate("AccountUI", "..."))
        self.toolButton_51.setText(_translate("AccountUI", "..."))
        self.toolButton_52.setText(_translate("AccountUI", "..."))
import resource_rc
