# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppSettings(object):
    def setupUi(self, AppSettings):
        AppSettings.setObjectName("AppSettings")
        AppSettings.resize(498, 243)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AppSettings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(AppSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox_5 = QtWidgets.QGroupBox(AppSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.qt_dialog = QtWidgets.QRadioButton(self.groupBox_5)
        self.qt_dialog.setObjectName("qt_dialog")
        self.gridLayout_24.addWidget(self.qt_dialog, 0, 1, 1, 1)
        self.native_dialog = QtWidgets.QRadioButton(self.groupBox_5)
        self.native_dialog.setChecked(True)
        self.native_dialog.setObjectName("native_dialog")
        self.gridLayout_24.addWidget(self.native_dialog, 0, 0, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_24)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_7 = QtWidgets.QGroupBox(AppSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.dark = QtWidgets.QRadioButton(self.groupBox_7)
        self.dark.setChecked(True)
        self.dark.setObjectName("dark")
        self.gridLayout_25.addWidget(self.dark, 0, 0, 1, 1)
        self.light = QtWidgets.QRadioButton(self.groupBox_7)
        self.light.setObjectName("light")
        self.gridLayout_25.addWidget(self.light, 0, 1, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_25)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(AppSettings)
        QtCore.QMetaObject.connectSlotsByName(AppSettings)

    def retranslateUi(self, AppSettings):
        _translate = QtCore.QCoreApplication.translate
        AppSettings.setWindowTitle(_translate("AppSettings", "Form"))
        self.label.setText(_translate("AppSettings", " Settings"))
        self.groupBox_5.setTitle(_translate("AppSettings", "General settings"))
        self.qt_dialog.setText(_translate("AppSettings", "Use QT File Dialog"))
        self.native_dialog.setText(_translate("AppSettings", "Use Native File Dialog"))
        self.groupBox_7.setTitle(_translate("AppSettings", "Theme setting"))
        self.dark.setText(_translate("AppSettings", "Dark mode"))
        self.light.setText(_translate("AppSettings", "Light mode"))
