name: jpg2pdf
base: core18 # the base snap is the execution environment for this snap
version: '2024.1.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Convert jpg jpeg png bmp svg tiff images to pdf format with encryption
description: jpeg2pdf is a powerful pdf converter for converting any images like jpg jpeg png bmp svg tiff to standard pdf format with encryption and other addition features
grade: stable # must be 'stable' to release into candidate/stable channels  / before dev use devel
confinement: strict # use 'strict' once you have the right plugs and slots / before dev use devmode

icon: snap/gui/icon.png

architectures:
  - build-on: [amd64]

apps:
  jpg2pdf:
    command: bin/desktop-launch python3 $SNAP/jpg2pdf.py
    plugs:
       - home
       - gsettings
       - network
       - network-bind
       - network-status
       - desktop
       - desktop-legacy
       - x11
       - unity7
       - wayland
       - opengl
       - optical-drive
       - removable-media
    desktop: jpg2pdf.desktop
    environment:
      DISABLE_WAYLAND: 1

plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  pyqt5-runtime-lite:
    interface: content
    target: $SNAP/pyqt5-runtime-lite
    default-provider: pyqt5-runtime-lite


parts:
  desktop-gui:
    plugin: dump
    source: src/
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${SNAPCRAFT_PART_SRC}/jpg2pdf.desktop
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/
      cp -rf ${SNAPCRAFT_PART_SRC}/jpg2pdf.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/jpg2pdf.desktop


  snap-launcher:
    plugin: dump
    source: snap_launcher/

  jpg2pdf:
      plugin: python
      python-version: python3
      source: .
      python-packages:
          - requests
          - cryptography
          - fpdf2
          - Pillow
          - pikepdf
      build-attributes: [ keep-execstack ]
