name: jpg2pdf
base: core22
version: '2026.7.2'
summary: Convert JPG, PNG, SVG, TIFF and BMP images into encrypted PDF files
description: JPG2PDF converts JPG, JPEG, PNG, BMP, SVG, TIFF and many other image formats into high-quality PDF documents.
grade: stable
confinement: strict

icon: snap/gui/icon.png

architectures:
  - build-on: [amd64]

environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/pyqt5-runtime-core22-lite

apps:
  jpg2pdf:
    command: bin/desktop-launch python3 $SNAP/jpg2pdf.py
    plugs:
       - home
       - gsettings
       - network
       - network-bind
       - network-status
       - desktop
       - desktop-legacy
       - x11
       - unity7
       - wayland
       - opengl
       - removable-media
    desktop: jpg2pdf.desktop
    environment:
      DISABLE_WAYLAND: 1

plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  pyqt5-runtime-core22-lite:
    interface: content
    target: $SNAP/pyqt5-runtime-core22-lite
    default-provider: pyqt5-runtime-core22-lite


parts:
  desktop-gui:
    plugin: dump
    source: src/
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${SNAPCRAFT_PART_SRC}/jpg2pdf.desktop
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/
      cp -rf ${SNAPCRAFT_PART_SRC}/jpg2pdf.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/jpg2pdf.desktop


  snap-launcher:
    plugin: dump
    source: snap_launcher/

  jpg2pdf:
      plugin: python
      source: .
      python-packages:
          - requests
          - cryptography
          - fpdf2
          - Pillow
          - pikepdf